// Result & errors
export { type Err, err, type Ok, ok, type Result, unwrap, unwrapOr } from './result.js'
export {
  type AstrotimeError,
  InvalidTimeError,
  isAstrotimeError,
  LeapSecondTableError,
  TimeParseError,
} from './errors.js'
export type { StringWithHints } from './types.js'

// Calendar
export {
  type CivilDate,
  civilFromDays,
  civilFromOrdinal,
  dayOfYear,
  daysFromCivil,
  daysInMonth,
  daysInYear,
  isLeapYear,
} from './calendar.js'

// Duration
export {
  absDuration,
  addDurations,
  compareDurations,
  type Duration,
  type DurationComponents,
  type DurationFormat,
  type DurationParts,
  duration,
  durationFromDays,
  durationFromHours,
  durationFromMillis,
  durationFromMinutes,
  durationFromNanos,
  durationFromSeconds,
  durationsEqual,
  durationToComponents,
  durationToDays,
  durationToHours,
  durationToMillis,
  durationToMinutes,
  durationToNanos,
  durationToSeconds,
  formatDuration,
  isDuration,
  isNegativeDuration,
  NANOS_PER_DAY,
  NANOS_PER_HOUR,
  NANOS_PER_MICRO,
  NANOS_PER_MILLI,
  NANOS_PER_MINUTE,
  NANOS_PER_SECOND,
  negateDuration,
  parseDuration,
  parseDurationOrThrow,
  scaleDuration,
  subtractDurations,
  ZERO_DURATION,
} from './duration.js'

// Leap seconds
export {
  deltaAtUnixSeconds,
  freezeLeapSecondTable,
  IERS_LEAP_SECONDS,
  type LeapSecondEntry,
  type LeapSecondTable,
  parseLeapSecondsList,
  PRE_1972_DELTA_AT,
  validateLeapSecondTable,
} from './leap-seconds.js'

// Instant
export {
  addDuration,
  type CalendarFields,
  type CivilDateTime,
  type CivilFields,
  clampInstant,
  compareInstants,
  deltaAt,
  durationBetween,
  type Instant,
  instantFromDate,
  instantFromOffsetMillis,
  instantFromOffsetSeconds,
  instantFromTaiNanos,
  instantFromUnixMillis,
  instantFromUnixNanos,
  instantFromUnixSeconds,
  instantFromUtc,
  instantNow,
  instantRange,
  instantsEqual,
  instantToDate,
  instantToOffsetMillis,
  instantToOffsetSeconds,
  instantToTaiNanos,
  instantToUnixMillis,
  instantToUnixNanos,
  instantToUnixSeconds,
  instantToUtc,
  isAfter,
  isBefore,
  isInstant,
  isLeapSecond,
  isLeapSecondTableExpired,
  isUtcDefined,
  maxInstant,
  minInstant,
  type OrdinalFields,
  subtractDuration,
  UNIX_EPOCH_INSTANT,
  unixMillisResolutionNanos,
  UTC_START_INSTANT,
  type UtcOptions,
} from './instant.js'

// Scales
export {
  GPS_EPOCH_INSTANT,
  GPS_MINUS_TAI_NANOS,
  type GpsWeek,
  instantFromCivil,
  instantFromGpsSeconds,
  instantFromGpsWeek,
  instantFromJ2000Nanos,
  instantFromJ2000Seconds,
  instantFromJulianDate,
  instantFromJulianDateParts,
  instantFromModifiedJulianDate,
  instantFromScaleNanos,
  instantFromScaleSeconds,
  instantToCivil,
  instantToGpsSeconds,
  instantToGpsWeek,
  instantToJ2000Nanos,
  instantToJ2000Seconds,
  instantToJulianDate,
  instantToJulianDateParts,
  instantToModifiedJulianDate,
  instantToScaleNanos,
  instantToScaleSeconds,
  J2000_INSTANT,
  JD_J2000,
  JD_UNIX_EPOCH,
  type JulianDateParts,
  MJD_OFFSET,
  TIME_SCALE_LABELS,
  TIME_SCALES,
  type TimeScale,
  truncateInstant,
  type TruncateUnit,
  TT_MINUS_TAI_NANOS,
} from './scales.js'

// Format & parse
export {
  formatInstant,
  formatIso,
  type FormatOptions,
  formatOrdinal,
  type FractionPrecision,
  INSTANT_TOKEN,
  isValidFormatPattern,
  type IsoFormatOptions,
  unknownFormatTokens,
} from './format.js'
export {
  isValidInstant,
  type ParseError,
  type ParseOptions,
  parseInstant,
  parseInstantOrThrow,
} from './parse.js'
